### ISSUE TITLE
Storefront 2.0

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#159]
[Approved design prototype in Figma](https://www.figma.com/proto/OnZKcZ4pVbDLxuGThDodig/UTK-%7C-Design-v06?page-id=11561%3A229&node-id=11561-230&viewport=760%2C966%2C0.16&t=GBdr28WwN6vdSeKD-8&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=11561%3A230&hide-ui=1)

**Comment by reasterbrooknc** [comment]
Can we estimate out what it would take for wires, designs, and dev on this? Then perhaps move forward with wires and designs but TBD when we would want to dev it and make it available.

**Comment by reasterbrooknc** [comment]
Issue on component template, from Leigh: I think the dotted line borders were originally intended to separate the content chunks on the pattern documentation pages, correct? It seems as if all of the unordered lists are styled to have a full-width dotted line top border, and this style inserts some extra visual breaks in the content where they shouldn’t be. Is this something that could be backlogged and fixed in a future push?

**Comment by reasterbrooknc** [comment]
Related to #213 #214
