### ISSUE TITLE
Jumplinks on internal navigation jump a good bit below where the anchor is set

### ISSUE THREAD

**Issue by pikemurdy** [utkwdn/utkwds#404]
**Describe the bug**
Jumplinks on internal navigation jump a good bit below where the anchor is set

**WDS Theme Version**
1.2

**URL**
https://cci-dev.utk.edu/academics-and-programs/graduate-certificates/#Healthcare

**To Reproduce**
Go to any page w/internal nav and click on a jump link

**Expected behavior**
For the jump to land where the anchor is place or just a smidge above it

**Desktop (please complete the following information):**
Mac

**Comment by reasterbrooknc** [comment]
@pikemurdy this doesn't appear to be an issue with the jump links. A background color is being set on the containing block group and it is hiding the link that is set on the in-page navigation. When you strip out the background color on the containing group and only apply it to the in-page navigation unordered list, the jump links jump to the appropriate place. 

This is probably a larger issue of setting background colors manually rather than just using the patterns—unintended consequences.

**Comment by pikemurdy** [comment]
To make sure we're on the same page: The issue is if the in page navigation is sticky, there's no background by default, causing the content behind the links to be seen.

http://web.utk.edu/~mpurdy1/vid-test/jumplinks.mov

**Comment by reasterbrooknc** [comment]
This issue was addressed in 1.2.2. Closing!
